GLFW backend based on odin-glfw
ThisDrunkDane/odin-imgui pull request #8
Opened 2021-07-21 13:04 UTC by hstormo

2021-07-21 18:04 UTC, ThisDrunkDane requested changes

2021-07-21 18:04 UTC, ThisDevDane commented on impl/glfw/glfw.odin
> +state: GLFW_State;
Please do like the sdl implementation and pass this around. I would prefer not to force people to have globals if they don't want them. If they don't care they can always just use their own global variable in their own code.

You should also add it to the `Imgui_State` struct in your example like the SDL examples does.

2021-07-21 18:04 UTC, ThisDrunkDane commented on impl/glfw/glfw.odin
> +    if w > 0 && h > 0 do io.display_framebuffer_scale = { f32(display_w) / f32(w), f32(display_h) / f32(h) };
Just do this as a normal `if` statement instead of a single liner.

2021-07-21 18:04 UTC, ThisDrunkDane commented on examples/glfw_opengl/main.odin
> +show_demo_window := false;
Just to keep inline with the SDL example, moves this back to the `main` proc

2021-07-21 18:56 UTC, hstormo commented
The problem with the global variables is that they're accessed in the callbacks from glfw (key_callback etc). The only alternative I know is to use the window user pointer. I can do that in the example for `show_demo_window`, but doing it for GLFW_State would create a conflict for anyone using the user pointer for another purpose.

Another alternative is to leave it up to the user to chain the necessary callbacks and provide a pointer to the state struct. But, it would mean extra boilerplate for anyone not already using every callback that the implementation needs.

2021-07-21 21:56 UTC, ThisDrunkDane commented
I see, yea okay if that's just how GLFW works then keep it as global state.

2021-07-21 21:57 UTC, ThisDrunkDane commented on impl/glfw/glfw.odin
> +        io.display_size = { f32(w), f32(h) };
io.display_size shold still be set even if `w` & `h` are not above 0 (otherwise dear imgui doesn't know the display is so small

2021-07-22 18:23 UTC, hstormo commented
Should be good now.

2021-07-22 21:55 UTC, merged